version: '3.8'

services:
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
      args:
        - MYSQL_HOST
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/html
    logging:
      driver: journald
      options:
        tag: wordpress-logs
    networks:
      - inception
    ports:
      - 9000
    # depends_on:
    #   mariadb:
    #     condition: service_healthy
    restart: on-failure
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
      - DB:/var/lib/mysql
    logging:
      driver: journald
      options:
        tag: mariadb-logs
    networks:
      - inception
    ports:
      - 3306
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p", "$MYSQL_ROOT_PASSWORD"]
    #   timeout: 20s
    #   retries: 10
    restart: on-failure
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - WordPress:/var/www/html
    logging:
      driver: journald
      options:
        tag: nginx-logs
    networks:
      - inception
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: on-failure

volumes:
  DB:
    name: DB
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/DB
      o: bind
  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/WordPress
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
